apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources: 
    requests:
      storage: 4Gi
      
      
# accessModes:
=============== 
# ReadWriteOnce--> volume can be mounted as read-write by single node
# ReadWriteMany--> volume can be mounted as read-write by many node-----> supports nfs
# ReadOnlyMany--> volume can be mounted as read-only by many node
